### ISSUE TITLE
Incomprehension

### ISSUE THREAD

**Issue by ImpZeng** [billp/VPCCMCrypt#2]
A lot of variables don't understand, for example:iv、adata

**Comment by billp** [comment]
@ImpZeng 

iv = Initialization Vector: https://en.wikipedia.org/wiki/Initialization_vector
adata = Authentication Data or TAG:  https://en.wikipedia.org/wiki/CCM_mode

Please find more info here https://en.wikipedia.org/wiki/CCM_mode
